os:
  - linux

language: go

go:
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - master

go_import_path: github.com/corywalker/expreduce

script:
  - go test -v ./...
  - go test -v -race ./... -run Concurrency

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

notifications:
  email: false
