os:
  - linux

language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - master

go_import_path: github.com/corywalker/expreduce

install:
  - go get -u github.com/golang/lint/golint
script:
  - 'golint ./... | grep -v "be unexported" | grep -v "resourcesRubi"'
  - go test -v ./...
  - go test -v -race ./... -run Concurrency

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

notifications:
  email: false
